work_dir: ./work_dir/ntu60/xview/hagcn_joint

# feeder
feeder: feeders.feeder_ntu.Feeder
phase: test

test_feeder_args:
  data_path: /media/dataset/NTU_RGBD/CTR/NTU60_CV.npz
#  data_path: /media/dataset/NTU_RGBD/CTR/CV_example.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.hagcn_test.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  alpha: 1

# joint weights
weights: ./work_dir/ntu60/xview/hagcn_joint/runs-119-69972.pt
# bone weights
#weights: ./work_dir/ntu60/xview/magcn_bone_lab/runs-118-69384.pt
#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [60, 90]
warm_up_epoch: 0

# training
device: [0]
batch_size: 1
test_batch_size: 1
num_epoch: 120
nesterov: True
